Vera/Vera/Controllers/EditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vera.Domain.Entity.Identity;

namespace Vera.Controllers
{
    public class EditorController : Controller
    {
        // GET: Editor
        [Authorize(Roles = "manager, admin")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Vera/Vera/Controllers/PrintingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vera.Domain;
using Vera.Models;

namespace Vera.Controllers
{
    [Authorize(Roles = "admin")]
    public class PrintingController : Controller
    {
        private DatabaseContext _db = new DatabaseContext();

        // GET: Printing
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Format = new SelectList(_db.Formats, "Id", "Name");
            ViewBag.FormingType = new SelectList(_db.FormingTypes, "Id", "Name");
            ViewBag.Colorfulness = new SelectList(_db.Colorfulnesses, "Id", "Name");

            return View();
        }

        public decimal GetPrintingPrice(int? formatId, int? colorfulnessId)
        {
            if (formatId.HasValue && colorfulnessId.HasValue)
            {
                var colorfulnessPricePerFormats = _db.ColorfulnessPricePerFormats.FirstOrDefault(
                    x => x.Format.Id == formatId.Value && x.Colorfulness.Id == colorfulnessId.Value);
                return colorfulnessPricePerFormats.Price.Cost * colorfulnessPricePerFormats.Price.Currency.Rate;
            }
            return 0;
        }

        [HttpPost]
        public ActionResult Index(PrintingPriceViewModel printingVM)
        {
            if (printingVM.FormatId.HasValue && printingVM.ColorfulnessId.HasValue &&
                printingVM.NewCost.HasValue)
            {
                var colorfulnessPricePerFormat = _db.ColorfulnessPricePerFormats.FirstOrDefault(
                    x => x.Format.Id == printingVM.FormatId && x.Colorfulness.Id == printingVM.ColorfulnessId);

                if (printingVM.NewCost.Value > 0)
                {
                    colorfulnessPricePerFormat.Price.Cost = printingVM.NewCost.Value;
                    _db.SaveChanges();    
                }
                
            }
            ViewBag.Format = new SelectList(_db.Formats, "Id", "Name");
            ViewBag.FormingType = new SelectList(_db.FormingTypes, "Id", "Name");
            ViewBag.Colorfulness = new SelectList(_db.Colorfulnesses, "Id", "Name");
            return View();
        }
    }
}

Vera/Vera/Views/Printing/Index.cshtml
@model Vera.Models.PrintingPriceViewModel
@{
    ViewBag.Title = "Печать";
}
<!DOCTYPE html>

<html>
<head> 
    <script src="~/Scripts/printing-change.js"></script>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-8 col-md-6">

                <h2>Редактировать цену печати</h2>
                
                @using (@Html.BeginForm())
                {
                    <div class="input-group myInputGroup">
                        <span class="input-group-addon myInputGroupSpan" id="basic-addon1">Формат</span>
                        @Html.DropDownListFor(model => model.FormatId, ViewBag.Format as SelectList, "Выберите формат", new { @class = "form-control", required="required" })<br />
                        @*@Html.DropDownList("Format", ViewBag.Format as SelectList, "Выберите формат", new { @class = "form-control" })<br />*@
                    </div><br />

                    <div class="input-group myInputGroup">
                        <span class="input-group-addon myInputGroupSpan" id="basic-addon1">Цветность печати</span>
                        @Html.DropDownListFor(model => model.ColorfulnessId, ViewBag.Colorfulness as SelectList, "Выберите цветность печати", new { @class = "form-control", required = "required" })<br />
                        @*@Html.DropDownList("Colorfulness", ViewBag.Colorfulness as SelectList, "Выберите цветность печати", new { @class = "form-control" })<br />*@
                    </div><br />

                    <div class="input-group myInputGroup">
                        <span class="input-group-addon myInputGroupSpan" id="basic-addon1">Стоимость за лист</span>
                        @*@Html.EditorFor(model => model.NewCost, null, new { @class = "form-control" })*@
                        @Html.TextBoxFor(model => model.NewCost, new
                           {
                               @class = "form-control",
                               id = "printingPrice",
                               autocomplete = "off",
                               placeholder = "Выберите все значения",
                               required = "required" 
                           })
                    </div><br />

                    <div class="input-group myInputGroup">
                        <span class="input-group-addon myInputGroupSpan" id="basic-addon1">Валюта</span>
                        <input type="text" class="form-control" id="currency" aria-describedby="basic-addon1"
                               autocomplete="off"
                               value="RUB"
                               readonly="readonly">
                    </div><br />

                    <button type="submit" class="btn btn-primary btn-lg btn-block" id="savePrintingPrice">Сохранить новую стоимость печати</button>
                    @*<button type="reset" class="btn btn-default btn-lg btn-block" id="savePrintingPrice">Сбросить параметры</button>*@
                }
                <br />
            </div>
        </div>
        <br />
        <div>
            @Html.ActionLink("Вернуться на главную страницу редактора", "Index", "Editor")
        </div>
    </div>
</body>
</html>